baseurl = "/"
languageCode = "fr-fr"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
pagination.pagerSize = 5


[caches]
  [caches.images]
    dir = ':cacheDir/images'


# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 7

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  dateFormat = "02/01/2006"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.fr]
    languageName = "Français"
    title = "Thierry P."

    [languages.fr.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = "Thierry P."
      keywords = ""
      copyright = "qsdf"
      menuMore = "Autres liens"
      readMore = "Lire la suite"
      readOtherPosts = "Lire les autres articles"
      newerPosts = "Article récents"
      olderPosts = "Anciens articles"
      missingContentMessage = "Page introuvable..."
      missingBackButtonLabel = "Revenir à la page d'accueil"
      minuteReadingTime = "min de lecture"
      words = "mots"

      [languages.fr.params.logo]
        logoText = "Thierry P."
        logoHomeLink = "/"

      [languages.fr.menu]
        [[languages.fr.menu.main]]
          identifier = "articles"
          name = "Articles"
          url = "/posts"
          weight = 90

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'
